spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:taskdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Jakarta
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    time-zone: Asia/Jakarta

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always